### ISSUE TITLE
Question: on the satellite configuration

### ISSUE THREAD

**Issue by Gekkotron** [KiboOst/jeedom-jeerhasspy#2]
How do you install a satellite? I can't find anything for satellite installation on the Rhasspy documentation. 

I already tried with snips satellite but Rhasspy listen only first site-id from the MQTT settings. 

But it detects hot words from all site-ids.

Thanks

**Comment by KiboOst** [comment]
Basically, you keep wakeword but send other settings (STT, intent recognition etc) to the master.
Better go to https://community.rhasspy.org/ for such questions as this isn't related to the plugin itself ;-)
